/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.macauyeah.springboot.tutorial.openapiclient.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for ApiDateRequest
 */
class ApiDateRequestTest {
    private final ApiDateRequest model = new ApiDateRequest();

    /**
     * Model tests for ApiDateRequest
     */
    @Test
    void testApiDateRequest() {
        // TODO: test ApiDateRequest
    }

    /**
     * Test the property 'inputDate'
     */
    @Test
    void inputDateTest() {
        // TODO: test inputDate
    }

}
