/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.macauyeah.springboot.tutorial.openapiclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

/**
 * ApiDateRequest
 */
@JsonPropertyOrder({
  ApiDateRequest.JSON_PROPERTY_INPUT_DATE
})
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2025-06-03T15:44:01.488474300+08:00[Asia/Macau]", comments = "Generator version: 7.13.0")
public class ApiDateRequest {
  public static final String JSON_PROPERTY_INPUT_DATE = "inputDate";
  @jakarta.annotation.Nullable
  private OffsetDateTime inputDate;

  public ApiDateRequest() {
  }

  public ApiDateRequest inputDate(@jakarta.annotation.Nullable OffsetDateTime inputDate) {
    
    this.inputDate = inputDate;
    return this;
  }

  /**
   * Get inputDate
   * @return inputDate
   */
  @jakarta.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_INPUT_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public OffsetDateTime getInputDate() {
    return inputDate;
  }


  @JsonProperty(JSON_PROPERTY_INPUT_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInputDate(@jakarta.annotation.Nullable OffsetDateTime inputDate) {
    this.inputDate = inputDate;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ApiDateRequest apiDateRequest = (ApiDateRequest) o;
    return Objects.equals(this.inputDate, apiDateRequest.inputDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(inputDate);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ApiDateRequest {\n");
    sb.append("    inputDate: ").append(toIndentedString(inputDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

