/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package io.github.macauyeah.springboot.tutorial.openapiclient.api;

import io.github.macauyeah.springboot.tutorial.openapiclient.invoker.ApiClient;
import io.github.macauyeah.springboot.tutorial.openapiclient.model.ApiDateRequest;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.web.reactive.function.client.WebClient;

import com.fasterxml.jackson.databind.ObjectMapper;
import org.springframework.http.codec.json.Jackson2JsonDecoder;
import org.springframework.http.codec.json.Jackson2JsonEncoder;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;

import java.text.SimpleDateFormat;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for ApiControllerApi
 */
// @Disabled
public class ApiControllerApiTest {

    private final ApiControllerApi api = new ApiControllerApi();

    /**
     * 
     *
     * 
     */
    @Test
    public void postDateQueryTest() {
        ApiDateRequest apiDateRequest = new ApiDateRequest();
        apiDateRequest.setInputDate(OffsetDateTime.now());

        ObjectMapper mapper = new ObjectMapper();
        mapper.setDateFormat(new SimpleDateFormat());
        mapper.registerModule(new JavaTimeModule());
        WebClient webClient = WebClient.builder()
                .codecs(configurer -> {
                    configurer.defaultCodecs().jackson2JsonDecoder(new Jackson2JsonDecoder(mapper));
                    configurer.defaultCodecs().jackson2JsonEncoder(new Jackson2JsonEncoder(mapper));
                })
                .build();

        ApiControllerApi api2 = new ApiControllerApi(new ApiClient(webClient));
        LOG.debug("default web client postDateQuery:{}", api.postDateQuery(apiDateRequest).block());
        LOG.debug("create api2 by local web client postDateQuery:{}", api2.postDateQuery(apiDateRequest).block());

        String response = webClient.post().uri("http://localhost:8080/api/record").bodyValue(apiDateRequest).retrieve()
                .bodyToMono(String.class).block();
        LOG.debug("by local web client postDateQuery:{}", response);
    }

    private static Logger LOG = LoggerFactory.getLogger(ApiControllerApiTest.class);

}
