/*
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package io.github.macauyeah.springboot.tutorial.openapiclient.api;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

/**
 * API tests for ChildControllerApi
 */
@Disabled
public class ChildControllerApiTest {

    private final ChildControllerApi api = new ChildControllerApi();

    
    /**
     * 
     *
     * 
     */
    @Test
    public void directCallTest()  {
        // uncomment below to test the function
        //String response = api.directCall().block();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     */
    @Test
    public void postfixTest()  {
        // uncomment below to test the function
        //String response = api.postfix().block();

        // TODO: test validations
    }
    
}
